[project]
name = "doom-rl-speedrun"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ultralytics>=8.3.145",
    "vizdoom>=1.2.4",
]
